# syntax=docker/dockerfile:1
# Production Dockerfile
#
# Base images are pinned by digest so a rebuild gets exactly the same base;
# Dependabot (docker ecosystem) proposes digest bumps.
FROM node:22-alpine@sha256:0a7108bf6c7bf5de370ffb1a3ed6be93d405b43ff159f681a8d18c0e2bc2e402 AS base

# Install pnpm and OpenSSL dependencies for Prisma
RUN apk add --no-cache openssl

# Install pnpm, pinned to match package.json's "packageManager" field so the
# image build doesn't break when a new pnpm major changes install behavior
# (e.g. pnpm 10's package-manager identity check, which failed here on an
# unpinned install against a lockfile generated by pnpm 9)
RUN npm install -g pnpm@9.12.2

# Set working directory
WORKDIR /app

# Set Prisma to use binary engine (let Prisma auto-detect the correct binary)
ENV PRISMA_QUERY_ENGINE_TYPE=binary

# Non-root runtime user, created before the copies below so they can be owned
# directly with --chown instead of a whole-tree chown afterwards.
RUN addgroup -g 1001 -S nodejs && adduser -S nextjs -u 1001 -G nodejs

# Copy package files first for better layer caching
COPY package.json pnpm-lock.yaml ./

# Copy prisma schema (needed for postinstall script)
COPY prisma ./prisma

# Install all dependencies (including devDependencies for build)
RUN pnpm install --frozen-lockfile

# Generate Prisma client
RUN pnpm prisma generate

# Copy source code
COPY . .

# Build-time configuration. .env.production is no longer in the build context
# (2026-09-22 audit, H-B2): docker-compose.prod.yml passes the values the build
# needs. NEXT_PUBLIC_* are compiled into the browser bundle by design, so they are
# public anyway; they live only in this build stage, not the runtime image.
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_SENTRY_DSN
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG SENTRY_ORG
ARG SENTRY_PROJECT
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL \
    NEXT_PUBLIC_SENTRY_DSN=$NEXT_PUBLIC_SENTRY_DSN \
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY \
    SENTRY_ORG=$SENTRY_ORG \
    SENTRY_PROJECT=$SENTRY_PROJECT

# Build the application (prebuild runs type-check and lint). The webpack cache
# (~600 MB) is only useful to the next build on the same machine; left in, it is
# copied into the runtime image with the rest of .next.
# The Sentry token (source-map upload) arrives as a BuildKit secret: mounted for
# this one command, never written to a layer or the image history. Absent (as in
# CI), the build simply skips the upload.
RUN --mount=type=secret,id=sentry_auth_token,required=false \
    SENTRY_AUTH_TOKEN="$(cat /run/secrets/sentry_auth_token 2>/dev/null || true)" \
    pnpm run build && rm -rf .next/cache

# Copy Prisma client to a location that won't be excluded by .dockerignore
RUN find node_modules -name ".prisma" -type d | head -1 | xargs -I {} cp -r {} /tmp/prisma-client || \
    (echo "Prisma client not found in node_modules" && \
     echo "Checking for Prisma client in .pnpm directories..." && \
     find node_modules/.pnpm -name ".prisma" -type d | head -1 | xargs -I {} cp -r {} /tmp/prisma-client || \
     (echo "Prisma client still not found" && find node_modules -name "*prisma*" -type d && exit 1))

# Production stage
FROM node:22-alpine@sha256:0a7108bf6c7bf5de370ffb1a3ed6be93d405b43ff159f681a8d18c0e2bc2e402 AS production

# Install pnpm and OpenSSL dependencies for Prisma
RUN apk add --no-cache openssl

# Install pnpm, pinned to match package.json's "packageManager" field so the
# image build doesn't break when a new pnpm major changes install behavior
# (e.g. pnpm 10's package-manager identity check, which failed here on an
# unpinned install against a lockfile generated by pnpm 9)
RUN npm install -g pnpm@9.12.2

# Set working directory
WORKDIR /app

# Set Prisma to use binary engine (let Prisma auto-detect the correct binary)
ENV PRISMA_QUERY_ENGINE_TYPE=binary

# Non-root runtime user, created before the copies below so they can be owned
# directly with --chown instead of a whole-tree chown afterwards.
RUN addgroup -g 1001 -S nodejs && adduser -S nextjs -u 1001 -G nodejs

# Copy package files
COPY package.json pnpm-lock.yaml ./

# Copy prisma schema
COPY prisma ./prisma

# Temporarily disable postinstall script
RUN npm pkg delete scripts.postinstall

# Install production dependencies plus necessary runtime tools
RUN pnpm install --frozen-lockfile --prod && pnpm add -D prisma tsx

# Copy generated Prisma client from build stage
COPY --from=base --chown=nextjs:nodejs /tmp/prisma-client ./node_modules/.prisma

# Copy built application
COPY --from=base --chown=nextjs:nodejs /app/.next ./.next
COPY --from=base --chown=nextjs:nodejs /app/public ./public
COPY --from=base --chown=nextjs:nodejs /app/next.config.js ./

# Copy setup scripts
COPY --chown=nextjs:nodejs scripts/setup-prod.js ./

# prisma/seed.ts imports shared definitions (chapters, membership tiers) from
# src/lib. The seed is a one-off run from this image (the `seed` service in
# docker-compose.prod.yml) via tsx, so that module has to ship with it or seeding
# fails with MODULE_NOT_FOUND.
COPY --chown=nextjs:nodejs src/lib ./src/lib

# Only the directory itself and the pieces Next writes to (.next/cache) are owned
# by the runtime user; node_modules stays root-owned and read-only. The former
# `chown -R nextjs:nodejs /app` rewrote every file in node_modules into a new
# image layer and took over 20 minutes on the production host per deploy.
RUN chown nextjs:nodejs /app

# Switch to non-root user
USER nextjs

# Expose port. (5555 was Prisma Studio, which runs in its own opt-in container.)
EXPOSE 3000

# Set environment variable
ENV NODE_ENV=production

# Apply migrations, then start. Seeding is not part of startup any more.
CMD ["sh", "-c", "node setup-prod.js && pnpm start"] 