version: '3.8'

services:
  # PostgreSQL Database for local development
  postgres:
    image: postgres:15-alpine
    container_name: basa-postgres-local
    env_file:
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
    networks:
      - basa-local-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U basa_user -d basa_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # BASA Application (Local Development)
  basa-app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: basa-app-local
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    environment:
      # Use hardcoded DATABASE_URL for local
      - DATABASE_URL=postgresql://basa_user:basa_password@postgres:5432/basa_dev
      # Override NEXTAUTH_URL for local development
      - NEXTAUTH_URL=http://localhost:3000
      # Override NEXT_PUBLIC_APP_URL for local development
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      # Ensure we're in development mode
      - NODE_ENV=development
    volumes:
      # Mount the entire project for live development
      - .:/app
      # Exclude node_modules to avoid conflicts
      - /app/node_modules
      - /app/.next
    networks:
      - basa-local-network
    depends_on:
      postgres:
        condition: service_healthy
    # No restart policy for local development - we want to control it manually
    stdin_open: true
    tty: true

  # Prisma Studio (Local Development)
  prisma-studio:
    image: node:18-alpine
    container_name: basa-prisma-studio-local
    working_dir: /app
    command: ["sh", "-c", "npm install -g pnpm && pnpm install --frozen-lockfile && pnpm prisma studio --port 5555 --hostname 0.0.0.0"]
    env_file:
      - .env.development
    volumes:
      - ./prisma:/app/prisma:delegated
      - ./package.json:/app/package.json:delegated
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml:delegated
    ports:
      - "5555:5555"
    networks:
      - basa-local-network
    depends_on:
      - postgres

volumes:
  postgres_data_local:

networks:
  basa-local-network:
    driver: bridge 