services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: basa-postgres-dev
    environment:
      POSTGRES_DB: basa_dev
      POSTGRES_USER: basa_user
      POSTGRES_PASSWORD: basa_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - basa-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U basa_user -d basa_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # BASA Application (Development)
  basa-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: basa-app-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://basa_user:basa_password@postgres:5432/basa_dev
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-dev-secret-key-here
      # Add other environment variables as needed
      - STRIPE_SECRET_KEY=your-stripe-secret-key
      - STRIPE_PUBLISHABLE_KEY=your-stripe-publishable-key
      - MAILGUN_API_KEY=your-mailgun-api-key
      - MAILGUN_DOMAIN=your-mailgun-domain
      - SENTRY_DSN=your-sentry-dsn
    volumes:
      # Map the entire project directory for real-time updates
      - .:/app
      # Exclude node_modules to avoid conflicts
      - /app/node_modules
      # Exclude .next to avoid conflicts
      - /app/.next
    networks:
      - basa-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  basa-network:
    driver: bridge 