-- Update MembershipTier enum to include all the new values
ALTER TYPE "MembershipTier" ADD VALUE IF NOT EXISTS 'MEETING_MEMBER';
ALTER TYPE "MembershipTier" ADD VALUE IF NOT EXISTS 'ASSOCIATE_MEMBER';
ALTER TYPE "MembershipTier" ADD VALUE IF NOT EXISTS 'TRIO_MEMBER';
ALTER TYPE "MembershipTier" ADD VALUE IF NOT EXISTS 'CLASS_RESOURCE_MEMBER';
ALTER TYPE "MembershipTier" ADD VALUE IF NOT EXISTS 'NAG_RESOURCE_MEMBER';
ALTER TYPE "MembershipTier" ADD VALUE IF NOT EXISTS 'TRAINING_RESOURCE_MEMBER'; 