#!/bin/bash

# Local Development Help Script
# This script shows all available local development commands

echo "🚀 BASA Local Development Commands"
echo "=================================="
echo ""
echo "📋 Available Scripts:"
echo "  ./scripts/dev-local.sh     - Start local development environment"
echo "  ./scripts/stop-local.sh    - Stop local development environment"
echo "  ./scripts/local-dev-help.sh - Show this help message"
echo ""
echo "🔧 Manual Commands:"
echo "  # Start development"
echo "  docker-compose -f docker-compose.local.yml up --build"
echo ""
echo "  # Stop development"
echo "  docker-compose -f docker-compose.local.yml down"
echo ""
echo "  # View logs"
echo "  docker-compose -f docker-compose.local.yml logs -f"
echo ""
echo "  # View logs for specific service"
echo "  docker-compose -f docker-compose.local.yml logs -f basa-app"
echo "  docker-compose -f docker-compose.local.yml logs -f postgres"
echo ""
echo "  # Access container shell"
echo "  docker-compose -f docker-compose.local.yml exec basa-app sh"
echo ""
echo "  # Run database migrations"
echo "  docker-compose -f docker-compose.local.yml exec basa-app pnpm prisma migrate dev"
echo ""
echo "  # Reset database"
echo "  docker-compose -f docker-compose.local.yml down -v"
echo "  docker-compose -f docker-compose.local.yml up --build"
echo ""
echo "🌐 Access Points:"
echo "  App: http://localhost:3000"
echo "  Database: localhost:5433"
echo ""
echo "📁 Key Files:"
echo "  docker-compose.local.yml - Local development configuration"
echo "  Dockerfile.local         - Local development Docker image"
echo "  .env.development         - Development environment variables" 