name: Debug Workflow

on:
  push:
    branches: [dev]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: Debug step
      run: |
        echo "GitHub Actions are working!"
        echo "Branch: ${{ github.ref }}"
        echo "Event: ${{ github.event_name }}" 